### ISSUE TITLE
script not loading

### ISSUE THREAD

**Issue by BigGod12** [slimdestro/phonenumber#1]
Hello, i`m having issue running the script = package command-line-arguments is not a main package
any help with this please

**Comment by mukul-kumar-mishra** [comment]
`go mod tidy` should fix this :)
Please refer sample usage from README file(_updated_)
You can also just `go get [this_repo]` and call `phonescript.GenerateNumbers(10000])` in your module.

**Comment by BigGod12** [comment]
thank you for replying...i`m new to go lang

**Comment by mukul-kumar-mishra** [comment]
Closing!
